app:
  domain: 'app.example.org'
  port: 3000
  apiRoot: '/api'
  staticRoot: 'public'
  templateRoot: 'src/templates'
  extensions:
    - './src/extensions'

email:
  from: 'no-reply@example.org'

logging:
  level: 'debug'

auth:
  issuer: 'app.example.org'
  tokenMaxAge: 86400