app:
  domain: 'app.example.org'
  port: 3000
  apiRoot: '/api'
  staticRoot: 'public'
  templateRoot: 'src/templates'
  extensionFilePattern: '*.ts'
  extensionRoots:
    - './src/extensions'

notification:
  fromEmail: 'no-reply@example.org'
  outBoundRetentionDays: 7

logging:
  level: 'debug'

auth:
  issuer: 'app.example.org'
  tokenMaxAgeSeconds: 300
  sessionMaxAgeSeconds: 86400
  rootUser: 'root'
  anonymousUser: 'anonymous'
  defaultUsers:
    - 'kai.y.ching@gmail.com/Welcome123!'