app:
  domain: 'app.example.org'
  port: 3000
  apiRoot: '/api'
  staticRoot: 'public'
  templateRoot: 'src/templates'
  extensions:
    - './src/extensions'

notification:
  fromEmail: 'no-reply@example.org'
  outBoundRetentionDays: 7

logging:
  level: 'debug'

auth:
  issuer: 'app.example.org'
  tokenMaxAgeSeconds: 300
  sessionMaxAgeSeconds: 86400