import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect } from 'react';
import { Button } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  useEffect(() => {
    fetch('/api/health');
  }, []);

  return (
    <>
      <Head>
        <title>New application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Button variant="contained">hello</Button>
      </main>
    </>
  );
}
